name: Build site

on:
  push:
    branches:
      - master-v2
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Clean and install dependencies
        run: |
          rm -rf node_modules
          rm -f pnpm-lock.yaml
          pnpm install
      - name: Generate Nuxt site
        run: pnpm exec nuxt generate
      - name: Deploy via FTP
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .output/public
