name: Build site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Patch unifont googleicons JSON parse (temporary workaround)
        run: |
          FILE=node_modules/unifont/dist/index.js
          if [ -f "$FILE" ]; then
            grep -q "XSSI_PATCH" "$FILE" || sed -i "s/JSON.parse(await r.text())/JSON.parse((await r.text()).replace(/^\\)\\]\\}'\\\\n?/, '')) \/* XSSI_PATCH *\//" "$FILE" || true
          fi

      - name: Generate Nuxt site
        run: npx nuxt generate

      - name: Deploy via FTP
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .output/public/
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
